### ISSUE TITLE
JQAdm: Deleting or Renaming 'default' site results in unrecoverable state

### ISSUE THREAD

**Issue by adimit** [aimeos/aimeos-core#103]
Version is from git, revision `7a3c80f27a00d779476222f6a480a03bbbbc51ec`, with Aimeos running in TYPO3 8.7.8.

When editing the sites in JQAdm → Locale → Sites, deleting the `default` site results in:

```
No item found for conditions: Array ( [locale.site.code] => default )

Aimeos\MShop\Exception thrown in file
[…] vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Common/Manager/Base.php in line 562.
```

This state can't be recovered from through the backend (as far as I know.) Inserting the corresponding row into the db results in a usable installation again:

```.sql
insert into mshop_locale_site VALUES (1,0,'default','Default','[]',0,1,2,1,NOW(),NOW(),'USER');
```

Where `USER` is any valid user name. However, the `editor` field doesn't have a foreign key constraint, which means you can just input anything there 🙂 

I propose guarding against removal of the `default` site, perhaps throwing an error when the user attempts to remove or rename it.

**Comment by adimit** [comment]
It seems the locale itself might also be affected. It was gone, and when trying to switch to the Expert interface, I got:

```
No site item available

Aimeos\MShop\Locale\Exception thrown in file
/var/www/stage/releases/32/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Locale/Item/Standard.php in line 69.

15 Aimeos\MShop\Locale\Item\Standard::getSite()


/var/www/stage/releases/32/html/typo3conf/ext/aimeos/Classes/Controller/ExtadmController.php:

00037: 
00038:   $locale = $this->getContextBackend()->getLocale();

00039:   $site = $loNo site item available

Aimeos\MShop\Locale\Exception thrown in file
/var/www/stage/releases/32/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Locale/Item/Standard.php in line 69.

15 Aimeos\MShop\Locale\Item\Standard::getSite()


/var/www/stage/releases/32/html/typo3conf/ext/aimeos/Classes/Controller/ExtadmController.php:

00037: 
00038:   $locale = $this->getContextBackend()->getLocale();

00039:   $site = $locale->getSite()->getCode();

00040:   $langid = 'en';
00041: 
cale->getSite()->getCode();

00040:   $langid = 'en';

```

I fixed it with a simple SQL query again:

```
insert into mshop_locale values (3,1,'de','EUR',1,1,NOW(),NOW(),'aleks');
```

Of course, you'd have to adapt the locale to your local requirements.

**Comment by aimeos** [comment]
Deleting things might always be dangerous! You already get a big warning when you try to delete items, but it seems you ignored that ;-)

In fact, you can rename the default site but then you have to reconfigure the default site name and this makes only sense in rare conditions.

You can recover from that easily by running the update script of the Aimeos extension in the Extension Manager.

BTW: The editor field is for logging only so a referencial integrity isn't desired.

**Comment by adimit** [comment]
Interesting. I didn't actually delete it, I just renamed it, which did not carry a big red warning. However, the effects were the same as deleting it.

**Comment by aimeos** [comment]
OK, in this case you are right! We will add a warning for this too

**Comment by aimeos** [comment]
Done :-)

![admin-site-warning](https://user-images.githubusercontent.com/8647429/33662884-e0047dd8-da8d-11e7-8d97-4f01fe10421f.png)
