### ISSUE TITLE
Text editors should be configured similar by default in expert and simple mode

### ISSUE THREAD

**Issue by AlbiWe** [aimeos/aimeos-core#109]
e.g. in the text editor of expert mode tables are allowed, but destroyed if one saved the product in easy mode

**Comment by aimeos** [comment]
The expert mode will be removed in the next version and you shouldn't rely on it.

Also, please remember that Aimeos is an e-commerce framework but not a CMS. There are specialized CMS like TYPO3 that can handle complex and indivigual pages much better. In that case, the CMS is responsible for the content and you only need to add a stripped down version of the Aimeos catalog detail plugin (down to price and "add to basket" button only) to that page. Then, you have the best of both worlds
