### ISSUE TITLE
How can I create a customer account ?

### ISSUE THREAD

**Issue by hengsoheak** [aimeos/aimeos-core#110]
Sorry I try to understand and read your document make me difficult to understand how is it going on 
anyway I try to read code instead.
it is really hard to understand ur document now I'm trying to read code instead 

Sorry I get stuck to create a client account

**Comment by aimeos** [comment]
Which document do you refer to?

**Comment by hengsoheak** [comment]
Sorry I really don't understand now am trying to read code and follow the application structure instead read document
https://aimeos.org/docs/Developers#Themes

**Comment by aimeos** [comment]
Do you want to create a new client account on your own by using the customer manager or do you only want to understand how it works in the checkout process?

**Comment by hengsoheak** [comment]
I want those with customer account manager

**Comment by aimeos** [comment]
Which environment do you use? Laravel?

**Comment by hengsoheak** [comment]
Yes, I'm using Laravel 5.5.*

**Comment by aimeos** [comment]
You can have a look there how to create a new customer account:
https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/Command/AccountCommand.php#L164

Here you can see how to get the required context in different environments (FE, BE, CLI):
https://aimeos.org/docs/Laravel/Extend_Aimeos
