### ISSUE TITLE
Bug: MW lib/DB/Manager/PDO

### ISSUE THREAD

**Issue by flobee** [aimeos/aimeos-core#115]
Hallo Norbert
/lib/mwlib/src/MW/DB/Manager/PDO.php

Es gibt ein Problem:
- In den tests ein "SET @@session.wait_timeout  = 1" setzen und dann zwei Sekunden warten bevor ein test startet. Und dann werden vermutlich die Probleme klar.
Der Pool an Verbindungen funktioniert nur solange die default "wait_timeout" nicht greift.
Beispiel: Ein was auch immer z.B. "Job" Domain Import Prozess dauert über 10min (default wait_timeout in mysql/mariadb) wo keine DB Verbindung benötigt wird und dann soll ein Item gespeichert werden. PDO muss noch loser oder singleton werden :(

**Comment by aimeoscom** [comment]
Der Session Timeout wird nur zum Problem wenn Du solange in einer Transaktion bist:
https://github.com/aimeos/aimeos-core/blob/master/lib/mwlib/src/MW/DB/Statement/Base.php#L184

Ich würde Dir raten Deinen Code umzustellen, damit Du nicht so lange eine Transaktion offen hältst. Dann funktioniert auch der Reconnect ohne Probleme nach einem Timeout.

**Comment by flobee** [comment]
Danke für Hinweise! Transaktionen wolle ich nicht ansprechen :) :game_die: :gameover:
LG fb
