### ISSUE TITLE
Namespace of local decorators for managers

### ISSUE THREAD

**Issue by s-diez** [aimeos/aimeos-core#125]
Is there a reason why the namespace for local decorators for managers does not start with "Aimeos" or is this an oversight?

Global:
https://github.com/aimeos/aimeos-core/blob/7e3f5f2981800073e361de28e632a89fabce89b0/lib/mshoplib/src/MShop/Common/Manager/Sub/Traits.php#L90
Local:
https://github.com/aimeos/aimeos-core/blob/7e3f5f2981800073e361de28e632a89fabce89b0/lib/mshoplib/src/MShop/Common/Manager/Sub/Traits.php#L95

**Comment by aimeos** [comment]
That's definitively an error! Can you provide a PR with a patch?

**Comment by s-diez** [comment]
https://github.com/aimeos/aimeos-core/pull/126

**Comment by s-diez** [comment]
Githubs editor automatically adds a newline -.-.
I'll create a new merge request.

**Comment by aimeos** [comment]
A new release including your fix is available (aimeos/aimeos-core: 2018.07.20)
