### ISSUE TITLE
[Feature] Supplier address issues in checkout

### ISSUE THREAD

**Issue by nvindice** [aimeos/aimeos-core#129]
Another one: I currently have 2 problems using the "Supplier" provider for pickup delivery.

1) when I add multiple addresses to a supplier (BE), the user can't choose between them - this is bad if you have a supplier with multiple warehouses
2) the user will not be able to pickup his order because there is no ways for him to find out the actual pickup address! Even worse: the summary page and the email only display the internal supplier code, like "demo-1".

So I started working on the decorator to fix these issues and provide more functionality, but **I need a way to inject another string attribute during the process, which then will be displayed at the checkout page/email template.** What is the best way to achieve this?

**Comment by aimeos** [comment]
You can add arbitrary information as order service attributes which you can display in the summary and e-mail later on: https://aimeos.org/api/latest/class-Aimeos.MShop.Order.Item.Base.Service.Iface.html#_setAttributeItem

**Comment by nvindice** [comment]
Thank you, tried that and it works well. However, the additional attribute is missing in the confirmation e-mail. The decorator does not even seem to get called at all here. What am I missing?

**Comment by aimeos** [comment]
The decorator is only called on the checkout delivery page and you have to add the information you want to store as order service attribute. At the summary page and in the e-mail you can only display the information that have been stored as order service attributes.

**Comment by nvindice** [comment]
I use this code in the getConfigFE() function of my decorator:
`$service->setAttributeItem( new \Aimeos\MShop\Order\Item\Base\Service\Attribute\Standard( array(
	'order.base.service.attribute.code' => 'delivery-supplier.address',
	'order.base.service.attribute.value' => $addressShort,
) ) );`
It definitely gets executed, the information is displayed at the summary page automatically, but it's missing in the e-mail...

**Comment by aimeos** [comment]
Is it stored in the `mshop_order_base_service_attr` table for the order?
If it is available it should be displayed: 
- https://github.com/aimeos/ai-client-html/blob/master/client/html/templates/common/summary/service-standard.php
- https://github.com/aimeos/ai-client-html/blob/master/client/html/templates/email/common/text-summary-service-partial-standard.php

**Comment by nvindice** [comment]
No it isn't. So it looks like I did not fully understand the Controller system and the ´service´ object I use is just a copy, not a reference. I'm still a Aimeos newbie, sorry.

Where _should_ I use the ´setAttributeItem´ call? At which position in my decorator should I use which ´Service´ item?

**Comment by aimeos** [comment]
`saveOrderBase()` is not meant to be used during the checkout process.

You can use the `setConfigFE()` in your decorator to add more data to the order:
https://aimeos.org/api/latest/class-Aimeos.MShop.Service.Provider.Iface.html#_setConfigFE

**Comment by aimeos** [comment]
Merged into the Aimeos Core
