### ISSUE TITLE
Typo on PHPDoc @return on \Aimeos\MShop\Order\Item\Base\Iface:161

### ISSUE THREAD

**Issue by mfcanovas** [aimeos/aimeos-core#131]
https://github.com/aimeos/aimeos-core/blob/fb91a6145c47970f363e2b772a452520fba2d577/lib/mshoplib/src/MShop/Order/Item/Base/Iface.php#L161

**Comment by aimeos** [comment]
Thanks for the hint. Can you create a PR fixing the typo?

**Comment by aimeos** [comment]
Fixed: fc4e0028435ffe3404aa2100c88eefab4cf5f6b9
