### ISSUE TITLE
Basket / Order: PropertyAdd plugin does not work as expected

### ISSUE THREAD

**Issue by AndreasA** [aimeos/aimeos-core#133]
When using the `PropertyAdd` plugin, it does not really work as I would expect it too.

Instead of adding the properties of a certain type that one specifies in the plugin options to the basket, 

Only one property type can be "added" this way because:
```\Aimeos\MShop\Plugin\Provider\Order\PropertyAdd::addAttributes``` 
is defined, 

Furthermore, instead of the property type - as shown in the example - it is necessary to use e.g. ```product.property.value``` which is also why it only works for one property correctly, as the exists already check fails afterwards.

Using: 2018.10.12
With TYPO3 integration.

**Comment by aimeos** [comment]
The plugin has several issues as you say and it's time for a rewrite :-)
