### ISSUE TITLE
Combining of tier price products in the basket

### ISSUE THREAD

**Issue by guelzow** [aimeos/aimeos-core#135]
Hi everyone.

Aimeos may not combine tier price products in the basket.

How to reproduce:
1.) Create a simple tier price product without any options.
2.) Tier price should look like this: 100 € normal price, 50€ for more then 10.
3.) The customer adds 5 products to his basket, for 100€ each.
4.) Then the customer adds 11 products for 50€ each.

You then have two positions of the same product in the basket with 5 x 100€ and 11 x 50€.
Ideally it should combine both amounts together, resulting in 16 x 50€.

When adding a 5 products, and then adding 6 products, everything works as expected.
You get 11 x 50€ in the basket.

Tobi

**Comment by aimeos** [comment]
Thank you for your bug report. The issue has been fixed in https://github.com/aimeos/aimeos-core/commit/b8d33f2647b877612cd06af648c9ccea9072fd68 and will be part of the next release

**Comment by guelzow** [comment]
That was really quick. Thanks for fixing.  

:smiley:
