### ISSUE TITLE
Aggregating over attributes stopped working in 2018.10. Regression?

### ISSUE THREAD

**Issue by adimit** [aimeos/aimeos-core#139]
A recent update from `18.7.1` to `18.10.2` broke our attribute search. We think the [following commit](https://github.com/aimeos/ai-controller-frontend/commit/89c4f90d6f5ed7468f167a9f560e91e98ae79dc2#diff-0b317fde49909dbf9676876359e9cd59) may have been the culprit. In particular, attributes don't seem to be aggregated prior to search any more.

We've implemented a combined attribute search, where filtering by two different
(hidden) attributes at once is possible.

An example:

Given two attributes of the name `designer` and `manufacturer`, the function `\Aimeos\Controller\Frontend\Product\Standard.addFilterAttribute()` is
called with the parameter

    $oneIds = [
        designer => [ 1 ],
        manufacturer => [ 2 ]
    ]

This should mean that it filters for products which have **both** an attribute with ID `1` **and** one with ID `2`.
The function addFilterAttribute indicates that by setting the condition as

    index.attributeaggregate([1]) > 0 && index.attributeaggregate([2]) > 0

This behaviour doesn't exist anymore in 2017.10. The condition now becomes

    index.attribute.id = [1] && index.attribute.id = [2]

This results in the following SQL (simplified, I stripped away everything from
the query that does not pertain to the problem):

    SELECT DISTINCT mpro.`id`
      FROM `mshop_product` AS mpro
             LEFT JOIN `mshop_index_attribute` AS mindat USE INDEX (`idx_msindat_s_at_lt`, `unq_msindat_p_s_aid_lt`) ON mindat.`prodid` = mpro.`id`
     WHERE  ( mindat.`attrid` IN (2) AND mindat.`attrid` IN (1) )

This can never work: we're looking for an entry in `mshop_index_attribute` that
has **both** the `attrid` 2 **and** 1 at the same time. The SQL for the old
version 18.7.1 was:

    SELECT DISTINCT mpro.`id`
      FROM `mshop_product` AS mpro
             LEFT JOIN `mshop_index_catalog` AS mindca USE INDEX (`idx_msindca_s_ca_lt_po`, `unq_msindca_p_s_cid_lt_po`) ON mindca.`prodid` = mpro.`id`
     WHERE ( mpro.`siteid` IN (1) AND
            ( ( SELECT COUNT(DISTINCT mindat_agg.`attrid`)
                  FROM `mshop_index_attribute` AS mindat_agg
                 WHERE mpro.`id` = mindat_agg.`prodid`
                   AND mindat_agg.`attrid` IN ( 1 ) ) > 0 AND
                   ( ( SELECT COUNT(DISTINCT mindat_agg.`attrid`)
                         FROM `mshop_index_attribute` AS mindat_agg
                        WHERE mpro.`id` = mindat_agg.`prodid`
                          AND mindat_agg.`attrid` IN ( 2 ) ) > 0 ) ) )

Is it possible to get the old behaviour in the new version, i.e. did we not notice some breaking change in the API and we should be calling the controller differently now? So far, we just set the `f_oneId`-parameter like this: `?ai[f_oneid][manufacturer][0]=2&ai[f_oneid][designer][0]=1`.

**Comment by aimeos** [comment]
Indeed, that looks like a regression. We will see how we can fix that.

**Comment by aimeos** [comment]
We've added a new `index.attribute:oneof` search function that will create a similar SQL statement like you've posted and backported it to the 2018.10 branch. Can you please checkout
```
"aimeos/aimeos-core": "2018.10.x-dev",
"aimeos/ai-controller-frontend": "2018.10.x-dev"
```
and test if the results are now the expected ones?

**Comment by adimit** [comment]
Great, it works now!

**Comment by aimeos** [comment]
New releases have been tagged now :-)
