### ISSUE TITLE
[Feature] Flag for modified price in basket

### ISSUE THREAD

**Issue by nvindice** [aimeos/aimeos-core#141]
Hey there,

we have a case where a basket plugin manipulates a product's price under certain circumastances. This conflicts with the `ProductPrice` basket plugin, which checks for changed prices. I would like to introduce the flag `\Aimeos\MShop\Order\Item\Base\Product\Base::FLAG_FIXEDPRICE` and prevent the `ProductPrice` basket plugin from checking these products here: https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/src/MShop/Plugin/Provider/Order/ProductPrice.php#L69

I would offer to make a PR if you merge it afterwards...?

**Comment by aimeos** [comment]
When do you set your new flag?

**Comment by nvindice** [comment]
Only in my own plugin. But I guess there would be plenty of use cases for such a flag.

**Comment by nvindice** [comment]
Sorry, my PR yesterday was a bit rashly. I got a better proposal: We will use the already existing `isModified()` methods, but add a config option to the `ProductPrice` basket plugin to ignore changed prices with modifications (where `$price->isModified() == true`). What do you think?

**Comment by aimeos** [comment]
Might be a good idea but then it depends on the order of the plugins which may be very difficult to understand

**Comment by nvindice** [comment]
Not really - either the price is changed before the `ProductPrice` plugin is called - then `isModified()` will be `true` - or the price is changed afterwards, then the `ProductPrice` check won't do any harm.

**Comment by aimeos** [comment]
OK, let's give it a try :-)
