### ISSUE TITLE
[BUG] Image Quality ImageMagick

### ISSUE THREAD

**Issue by s-diez** [aimeos/aimeos-core#148]
There seems to be a bug/unintended change to how the quality of an image is calculated in \Aimeos\MW\Media\Image\Imagick. I suspect the change is from #f3e1eef4d44fef72fadb58dc6b4b5f50f51f5d89. As far as I can could test, `\Imagick::setImageCompressionQuality()` actually expects a quality instead of the inverse which `\Imagick::setImageCompression()` probably used.

You can easily test it with setting quality `controller.common.media.standard.options.image.quality` to 1 and set a product image. Then change it to 99 and add another image. For me the first image is ok while the second image has very poor quality. The default quality is 90.

Typo3 Version 8.7.24
Aimeos Version 2018.10.15

edit: I can supply a pull request changing `$this->image->setImageCompressionQuality( 100 - $quality ); // inverse quality scheme` to `$this->image->setImageCompressionQuality( $quality );`

**Comment by aimeos** [comment]
Yes, please create a PR for the change

**Comment by aimeos** [comment]
merged
