### ISSUE TITLE
[Bug] Execute in Migrations for specific table

### ISSUE THREAD

**Issue by s-diez** [aimeos/aimeos-core#151]
Hi,

Typo3: 8.7.24
Aimeos: 2019.04.3

In the migration `TablesUpdateCharsetCollation::checkTables` changes to a table are executed but the default resource ("db") is used no matter the table. I did run into some problems here, as we use a separate db (not the typo3 db) for aimeos, but the customer tables are in the typo3 db.
If those migrations are executed for the table "mshop_customer" they are executed on the resource "db" instead of "db-customer".

https://github.com/aimeos/aimeos-core/blob/6e3309639e882c2ce1c508765fe4c9a95ac90d4f/lib/mshoplib/setup/TablesUpdateCharsetCollation.php#L159

I am not familiar with this part of the code, but I would guess all executes in `TablesUpdateCharsetCollation::checkTables` would need the parameter `$name` dependent on the table the execute is aimed at.
If my guess is correct, I'm happy to provide a pull request.

Greetings Sebastian Diez

**Comment by aimeos** [comment]
Seems like a second "$rname" parameter für the mentioned line is missing to use the correct resource. Can you check and create a PR if so?

**Comment by s-diez** [comment]
> Can you check and create a PR if so?

I did a little test but it was limited as my database is actually a MariaDB 10.1, therefore now `checkMySqlCompatibility` prevents this part.

If I circumvent `checkMySqlCompatibility` the migration now fails with the expected key length error instead of "Missing table mshop_customer". To me this would mean it now works as intended, as the right db-resource is used. I could not test the part with "mshop_locale" but `$rname` should be "db-locale" otherwise `$table` could not be "mshop_locale".

**Comment by s-diez** [comment]
https://github.com/aimeos/aimeos-core/pull/153

**Comment by aimeos** [comment]
merged
