### ISSUE TITLE
[Bug] Availability based on status

### ISSUE THREAD

**Issue by s-diez** [aimeos/aimeos-core#155]
Hello Team of Aimeos,

Is it possible there is a bug in most implementations for `isAvailable` which checks the status? A text item marked as with status "archived" (-2) is still considered available. Shouldn't only items with status >= 1 be considered available?

The problem is the following code. Php only casts `0` to `false`, negative integers are considered `true`.

```php
(bool) $this->getStatus()
```

**Comment by aimeos** [comment]
Yes, that looks like a bug. Can you create a PR for fixing that?

**Comment by aimeos** [comment]
Fixed in https://github.com/aimeos/aimeos-core/pull/156
