### ISSUE TITLE
2018.x release

### ISSUE THREAD

**Issue by nvindice** [aimeos/aimeos-core#157]
Hi @aimeos Team,

may I ask for when the next 2018.10.x release is scheduled? We would like to launch our new shop in a couple of weeks and need the latest bug fixes / features - if possible on the stable branch..?

Best regards,
Nils

**Comment by aimeos** [comment]
Which packages do you need to be tagged?

**Comment by nvindice** [comment]
Only aimeos-core 2018.

**Comment by aimeos** [comment]
done

**Comment by nvindice** [comment]
Thank you!!!

**Comment by nvindice** [comment]
Could you please release-tag aimeos-core 2018.x and ai-client-html 2018.x one more time? Thank you!

**Comment by aimeos** [comment]
We will do it in 1-2 weeks

**Comment by nvindice** [comment]
Push

We would like to go live in a couple of days and need aimeos-core 2018.10, ai-client-html 2018.10 and aimeos-typo3 2018.10 with the current commits, please. Thank you!

**Comment by aimeos** [comment]
New releases for core and HTML client are possible, but for the TYPO3 extension you need to use 2018.10.x-dev until the new release end of this month is out

**Comment by nvindice** [comment]
Hm. Okay.

**Comment by nvindice** [comment]
So... could you please release core and HTML client? :-) Thanks!

**Comment by aimeos** [comment]
done

**Comment by nvindice** [comment]
Thank you! When can we expect the Typo3 extension update via Composer? Shall I remind you in a couple of days?

**Comment by aimeos** [comment]
ETA is around May, 29./30. You can stay at 2018.10.x-dev nevertheless as only bugfixes and minor improvements will happen in the future

**Comment by aimeos** [comment]
Are you satisfied using Aimeos? We would love to get feedback: https://aimeos.org/contact/#c1

**Comment by aimeos** [comment]
18.10.9 release happend yesterday
