### ISSUE TITLE
Logout does not clear personal information

### ISSUE THREAD

**Issue by nvindice** [aimeos/aimeos-core#163]
Hi @aimeos,

when I am logged in and start the checkout process, my address is automatically added to the basket, which is good.

When I return to the main page and log out, my address, billing details, etc are still part of the basket. Is this intended behaviour? When a user logs out, IMHO he wants his personal information to be "forgotten".

Should we clear the address and all service providers when a user logs out?

**Comment by aimeos** [comment]
AFAIK we have no control over the login/logout process and it depends on the host application if the session is cleared or not

**Comment by nvindice** [comment]
Not sure- if I understand the Autofill plugin correctly, `$context->getUserId() `either returns a valid user id (if a user is logged in) or `null `(if not). So the least we could do is to remove Addresses and Services from the basket, when a formerly logged in user is not logged in anymore. Only problem I see here: The plugin needs to detect if a user has been logged in last time the basket was updated. Otherwise everything would be cleared on each update when no user is logged in.

When is the `setCustomerId.after` event triggered? After a user logs in _and_ out?

**Comment by aimeos** [comment]
You won't remove these data permanently from baskets of guest buyers for which `getUserId()` also returns `null`. The `setCustomerId.after` event is triggered when the order is placed but the customer ID isn't removed when `getUserId()` returns `null` after logout.

Like said, this is something you have to care in the host application.

**Comment by nvindice** [comment]
I see. In the long run we could store something like a login status as a session variable and trigger a `logout` event when the status is set but no `userId` is available...?

I think this might be a useful feature.

**Comment by aimeos** [comment]
Aimeos is the wrong place for this IMHO and it should possible to do that in the host application, maybe via a hook or event

**Comment by nvindice** [comment]
I see your point. However, it should be possible to not just destroy the whole user session but keep the "non-personal" session information like "seen products" and the basket contents. This would be the same behaviour that most online shops have.

What if we add a function to the core which controls what happens at a logout event (fully configurable), and then add a hook in the host system (respectively aimeos_typo3 etc) to call it?

**Comment by aimeos** [comment]
That would be worth investigating. The big question is where should it be implemented on the Aimeos side? The session is populated at different levels, i.e. HTML clients, MShop order manager, etc.

**Comment by nvindice** [comment]
Well, you know the structure way better than I do... What would you suggest?

**Comment by aimeos** [comment]
It might be difficult to track which information should be removed and which one should stay. Perhaps, we should go the simple way first and add an option to the host system to clear the basket entirely.

**Comment by nvindice** [comment]
I thought of something like a configuration array:
```
clear-logout {
    basket = 0
    address = 1
    delivery = 1
    payment = 1
}
```

**Comment by aimeos** [comment]
The basket is a serialized object in the session, so you would have to retrieve the baskets (there can be several for different types, languages and currencies) from the session, change the basket and save them back to the session. Don't know if it's worth the time to do it in that detail.

**Comment by nvindice** [comment]
I don't think so, but I'd rather user Aimeos' functions for the removal. My idea is:
-> a hook in the host calls `\Aimeos\AB\CD::logout()`
-> this logout() method calls Aimeos' controller methods like `Aimeos\Controller\Frontend\Basket\Iface::deleteService()` (of course non-static in the current session)

**Comment by aimeos** [comment]
That's easy and I've checked the code, the data in other baskets of a user gets removed when migrating between sites/locales. So you could pass a new parameter to the `clear()` method of the basket controller and extend it (https://github.com/aimeos/ai-controller-frontend/blob/master/controller/frontend/src/Controller/Frontend/Basket/Iface.php#L36)

**Comment by nvindice** [comment]
Works pretty well. I extended the controller's `clear()` function and added a function `Base\Aimeos::logout()` in the `aimeos-typo3` package, but there is one problem I haven't solved yet: I have no access to the configuration made in the Page TS. I guess it's because the function gets called by a `felogin`-hook so there actually _is_ no page with TS. But where can I store the configuration? Do you have any idea?

**Comment by aimeos** [comment]
You can use the Extension configuration (https://github.com/aimeos/aimeos-typo3/blob/master/ext_conf_template.txt) which you can retrieve with:
https://github.com/aimeos/aimeos-typo3/blob/master/Classes/Base.php#L99

**Comment by nvindice** [comment]
I opened to PRs. I've tested all configurations on Typo3 v8, works fine.

What do you think? I'm open for suggestions if you would like to change anything.

**Comment by aimeos** [comment]
You take the indirection of setting and retrieving config options. I would pass a bitmap of the order base constants to the `clear()` method instead. This will also allow us to move the code to the order base item later

**Comment by nvindice** [comment]
Sorry, I'm not sure if I understand you correctly. Do you want me not pass the configuration via the `$localConfig` array in `$config = \Aimeos\Aimeos\Base::getConfig( $localConfig );` but rather via a bitmap?

Where do I get the contants from, should I create them in `\Aimeos\MShop\Order\Item\Base\Service\Base`?

**Comment by aimeos** [comment]
The constants are already there: https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/src/MShop/Order/Item/Base/Base.php#L28

Use something like this in the TYPO3 extension:
```
$parts = \Aimeos\MShop\Order\Item\Base::PARTS_ADDRESS | \Aimeos\MShop\Order\Item\Base::PARTS_COUPON;
$basket->clear( $parts );
```

**Comment by nvindice** [comment]
Oh I see. But do you want to not use any configuration at all? What about something like:

```
$parts = \Aimeos\MShop\Order\Item\Base::PARTS_NONE
if( \Aimeos\Aimeos\Base::getExtConfig( 'clearAddresses', 0 ) ) {
    $parts |= \Aimeos\MShop\Order\Item\Base::PARTS_ADDRESS;
}
if( \Aimeos\Aimeos\Base::getExtConfig( 'clearCoupons', 0 ) ) {
    $parts |= \Aimeos\MShop\Order\Item\Base::PARTS_COUPON;
}
// etc...
```

**Comment by aimeos** [comment]
Personally, I would say it's not necessary and a simple "clearBasket" option would be enough. If someone needs more control, he can overwrite the hook with his own code. By default it could be:
```
$basket->clear( \Aimeos\MShop\Order\Item\Base::PARTS_ALL );
```

**Comment by nvindice** [comment]
Okay. But where do I need the bit mask for? I could just use the original `clear()` method if nothing shall be configurable...

**Comment by aimeos** [comment]
Actually, we don't need it as long as you don't want to clear the basket partitially. For 2018.10, I would suggest to skip the bitmask parameter at all so the method stays in line with the interface definition.

**Comment by nvindice** [comment]
Okay. I've updated to `aimeos-typo3` PR and closed the `ai-controller-frontend` PR. If you like, you can use the code there for 2019.x, so that users have the possibility to decide which parts of the basket shall be cleared. If you don't think it's necessary, just leave it :-)

**Comment by aimeos** [comment]
Merged https://github.com/aimeos/aimeos-typo3/pull/103
