### ISSUE TITLE
strtolower to mb_strtolower for UTF-8 strings

### ISSUE THREAD

**Issue by flakyspark** [aimeos/aimeos-core#185]
Hi! I noticed wrong work of text-index because of strtolower usage instead of mb_strtolower 
Check places like these:
aimeos-core/lib/mshoplib/src/MShop/Index/Manager/Text/Standard.php:779 and :98
aimeos-core/lib/mshoplib/src/MShop/Index/Manager/Text/MySQL.php:66 
vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Index/Manager/Text/PgSQL.php:59

**Comment by aimeos** [comment]
Thanks for your hint! Can you create a pull request with the necessary changes in aimeos/aimeos-core?

**Comment by aimeos** [comment]
Already implemented
