### ISSUE TITLE
[Regression] Setup fails after update in 2018.10

### ISSUE THREAD

**Issue by nvindice** [aimeos/aimeos-core#194]
Hi @aimeos ,

since https://github.com/aimeos/aimeos-core/commit/1e66061cf021dfdcef9032cfeca37944d9b35493 my setup routine fails with following error message:
> Argument 1 passed to Doctrine\DBAL\Schema\Schema::__construct() must be of the type array, object given, called in /www/dev/vendor/aimeos/aimeos-core/lib/mshoplib/setup/TablesCreateMShop.php on line 191

When reverting the `array()` around the `$tables` var, everything seems to work fine.

Aimeos: 2018.10 latest on Typo3
DBAL version: 2.5.13
MySQL version: 5.7.29
PHP version: 7.2

**Comment by aimeos** [comment]
Thank you for reporting. 2018.10 is not supported any more and we won't release new versions. If you need a new version, please contact the Aimeos company as they offer extended LTS support.

As it's a minor issue that can be fixed quickly, we made a commit for that nevertheless: https://github.com/aimeos/aimeos-core/commit/5e79a1fbc39c1b96f8d1100ed4972b51b63cd04d

**Comment by nvindice** [comment]
Thank you!
