### ISSUE TITLE
"Migrate typeid to type" migration fails on MariaDB

### ISSUE THREAD

**Issue by jonaseberle** [aimeos/aimeos-core#201]
MariaDB 10.3.22

Introduced with
https://github.com/aimeos/aimeos-core/commit/f6f4c9f257fa6091d0624caad9ef2c33b391d539

When run via TYPO3 extension manager extension update:
<pre>
...
  Checking table "mshop_tag":                                         OK
  Checking table "mshop_text_list":                                   OK
Migrate typeid to type                                                
  Checking table "mshop_attribute":                                   
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'IN ( SELECT "code" FROM "mshop_attribute_type" AS t WHERE t."id" = "typeid" AND ' at line 1: UPDATE "mshop_attribute" SET "type" IN ( SELECT "code" FROM "mshop_attribute_type" AS t WHERE t."id" = "typeid" AND t."domain" = "domain" ) WHERE "type" = ''
#0 /var/www/html/src/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Task/Base.php(146): Aimeos\MW\DB\Statement\DBAL\Simple->execute()
#1 /var/www/html/src/vendor/aimeos/aimeos-core/lib/mshoplib/setup/TypesMigrateColumns.php(223): Aimeos\MW\Setup\Task\Base->execute('UPDATE "mshop_a...', 'db-attribute')
#2 /var/www/html/src/vendor/aimeos/aimeos-core/lib/mshoplib/setup/TypesMigrateColumns.php(131): Aimeos\MW\Setup\Task\TypesMigrateColumns->migrateData('db-attribute', Array)
#3 /var/www/html/src/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Manager/Multiple.php(114): Aimeos\MW\Setup\Task\TypesMigrateColumns->migrate()
...
</pre>

When run plain in MySQL:
<pre>
UPDATE mshop_attribute
SET type IN (SELECT code FROM mshop_attribute_type AS t WHERE t.id = "typeid" AND t.domain = "domain")
WHERE type = ''
</pre>
`Unsafe query: 'Update' statement without 'where' updates all table rows at once`

Swapping `IN` with `=` fixes the problem for MariaBD at least.

**Comment by aimeos** [comment]
Thank you for your hint. We've modified the statements so they should work now for MariaDB too like you've stated:
https://github.com/aimeos/aimeos-core/commit/38b5772ef4c2b29b92a563a06c3096416be9f2bc
