### ISSUE TITLE
[FEATURE] switch to TSL links

### ISSUE THREAD

**Issue by xerc** [aimeos/aimeos-core#202]
https://github.com/aimeos/aimeos-core/search?q=http%3A%2F%2Fdemo.aimeos.org

**Comment by aimeos** [comment]
What does that mean?

**Comment by xerc** [comment]
did you see the link? you are using non TSL links; alias "HTTP"

**Comment by aimeos** [comment]
The demo.aimeos.org domain already supports HTTPS. Can you create a PR changing http to https?

**Comment by xerc** [comment]
for expl. CHANGE
this `http://demo.aimeos.org/media/service/pickup.png`
to `https://demo.aimeos.org/media/service/pickup.png`
WITHIN the source-code @
https://github.com/aimeos/aimeos-core/blob/976fe71e007e2040998c46ac9697fd2fd4677bb7/lib/mshoplib/setup/unitperf/ServiceAddPerfData.php#L49
.. repeat

**Comment by aimeos** [comment]
yes

**Comment by xerc** [comment]
https://github.com/aimeos/aimeos-core/commit/3122da3324e6f6a630c05e273f3065b4e54997ba

**Comment by xerc** [comment]
btw/ there are a lot off OFFLINE links within i18n/po-files & more
- http://framework.zend.com/license/new-bsd
- http://www.transifex.com/aimeos/aimeos-core/language/bg/
- [..]

**Comment by aimeos** [comment]
> [3122da3](https://github.com/aimeos/aimeos-core/commit/3122da3324e6f6a630c05e273f3065b4e54997ba)

Can you create a pull request so we are able to merge it?

**Comment by aimeos** [comment]
> * http://framework.zend.com/license/new-bsd

This is a dead link indeed

> * http://www.transifex.com/aimeos/aimeos-core/language/bg/

The page is only avilable if you log into Transifex
