### ISSUE TITLE
Support gif files

### ISSUE THREAD

**Issue by mylgeorge** [aimeos/aimeos-core#205]
https://github.com/aimeos/aimeos-core/blob/d0040a1d45c49e34953dcf9f0eba15fb423e9180/lib/mwlib/src/MW/Media/Image/Imagick.php#L130

This line should be 
```
return $this->image->getImagesBlob();
```

**Comment by aimeos** [comment]
Does it support animated GIFs using `getImagesBlob()`?
If yes, could you please create a pull request with the change so we can merge it?

**Comment by aimeos** [comment]
Done in commit f1f87ac04dc5a95d0cc83e24ceb6d926eb6d363e
