### ISSUE TITLE
Search throws error in specific case (elasticsearch)

### ISSUE THREAD

**Issue by maxmessing** [aimeos/aimeos-core#207]
Description:
Aimeos throws an error if the user enters "tabs" in a specific lenght/combination (not 100% sure)

Steps to reproduce:
go to: http://typo3.gigacommerce.aimeos.com/index.php?id=43&ai%5Bcontroller%5D=Catalog&ai%5Baction%5D=list
enter: `TEST123123123	test	asd	test	tabs	\t\t\t 3.199 € 	2.285 €\t  04.01.2021\tFalse\t\t\t test.cx 	XXL	63	\t -   €` in the - replace \t with real "tabs" before (github is stripping them away) - search box an press enter.

Argument 2 passed to Aimeos\\MShop\\Index\\Manager\\Text\\Elastic::Aimeos\\MShop\\Index\\Manager\\Text\\{closure}() must be of the type array, null given, called in \/vendor\/aimeos\/aimeos-core\/lib\/mwlib\/src\/MW\/Criteria\/Expression\/Base.php on line 181

"A non-recoverable error occured"

**Comment by aimeos** [comment]
Tested your string with Aimeos 2019 and 2020 (MySQL full text search) and there's no problem and no non-recoverable error.
@nos3 Seems to be an ai-elastic problem

**Comment by nos3** [comment]
Yes, the change I made for @maxmessing uses json_decode() to get the parameter for searching but the function requires tabs to be encoded as `\t`. Same for new lines. It's fixed in the new ai-elastic release.
