### ISSUE TITLE
PayPalExpress.php

### ISSUE THREAD

**Issue by saappel** [aimeos/aimeos-core#208]
Can you change
CODE: SELECT ALL
$deliveryCosts
to
CODE: SELECT ALL
$service->getPrice()->getCosts()
There seems to be an undefined variable.

**Comment by aimeos** [comment]
Which Aimeos version are you using? Can you post the output of `composer show`?

**Comment by aimeos** [comment]
Seems to be an old version you are using. In 2020.10+ there's no undefined variable any more
