### ISSUE TITLE
[Bug] Server side email validation does not catch white space

### ISSUE THREAD

**Issue by guelzow** [aimeos/aimeos-core#213]
Hi everyone.

The server side email validation does not catch white spaces.
This allows customers to enter invalid addresses, when there is no additional frontend validation.

The Regex is located here:
https://github.com/aimeos/aimeos-core/blob/4e2be83ca708129d7f466d42bf8b02f23183b6c0/lib/mshoplib/src/MShop/Common/Item/Address/Base.php#L430

Tobi

**Comment by aimeos** [comment]
This seems to be the official regex for e-mail addresses:
```
(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
```

Can you check and create a PR if it works?

**Comment by guelzow** [comment]
Hi everyone.

Sorry, but this one does not let addresses through that contain upper case characters.

Tobi

**Comment by aimeos** [comment]
Using the "i" modifyer in the `/(...)/i` regex for case insensitive comparison should do the job.

**Comment by aimeos** [comment]
Fixed in this commit: https://github.com/aimeos/aimeos-core/commit/65e6f24b741bd7c43312028e95f9d98245a6d8e8
