### ISSUE TITLE
Unable to include stocks with products

### ISSUE THREAD

**Issue by sebastien-vedrine** [aimeos/aimeos-core#220]
I'm trying to import stocks asociated with my products, but it throws me an error.

![image](https://user-images.githubusercontent.com/33923690/115219352-bea10a00-a107-11eb-8322-a140e5906ad7.png)

It seems like you changed the mshop_stock structure recently (drop productcode and use productid instead) but it is still looking for the old column.

https://github.com/aimeos/aimeos-core/blob/eb2e68fe2f0bfb73c8ac806b9fa24ef2db6a9b85/lib/mshoplib/setup/StockMigrateProductId.php#L20-L26

Do you have any idea?

**Comment by aimeos** [comment]
The configuration for the stock manager has been updated to reflect that change:
https://github.com/aimeos/aimeos-core/blob/2021.04/lib/mshoplib/config/mshop/stock.php#L124-L151

Did you overwrite the SQL statements or is the old SQL statement still cached by APCu if enabled?
