### ISSUE TITLE
Syntax Error postgresql , DROP INDEX

### ISSUE THREAD

**Issue by MahmoudDevo** [aimeos/aimeos-core#221]
Hello,

"aimeos/aimeos-laravel": "~2021.04",

In the file:
vendor\aimeos\aimeos-core\lib\mshoplib\setup\StockMigrateProductId.php
This syntax is not correct for POSTGRESQL: 
`'unq_mssto_sid_pcode_ty' => 'DROP INDEX "unq_mssto_sid_pcode_ty" ON "mshop_stock"',`

Thank you

**Comment by MahmoudDevo** [comment]
Hi,
The correct syntax like : 
` 'unq_mssto_sid_pcode_ty' => 'DROP INDEX "unq_mssto_sid_pcode_ty"'`
thank you

**Comment by aimeos** [comment]
Migration has been fixed in dev-master and 2021.04.x-dev. Changes will be part of the next release.
