### ISSUE TITLE
UPGRADE from 2020.10 to 2021.04 in PostgreSQL

### ISSUE THREAD

**Issue by MahmoudDevo** [aimeos/aimeos-core#223]
Hello,
my first database (created by 2020.10) contains my data, I want to update to the latest version I followed the following steps:

    I created a new empty database and installed in last version, it works.
    But when I change the connection to the first database and run the following command:
` php ./artisan aimeos:setup`

I notice that the table "mshop_rule" is not created.

Thank you

**Comment by aimeos** [comment]
This seems to be the case if the migrations didn't run completely because an error occurs during the migration.
