### ISSUE TITLE
Syntax Error foreign key   

### ISSUE THREAD

**Issue by MahmoudDevo** [aimeos/aimeos-core#224]
Hello,
in the file: 
 **ext\ai-laravel\lib\custom\setup\CustomerRemoveConstraints.php**
This syntax is not correct IN POSTGRESQL : 
`ALTER TABLE "users_address" DROP FOREIGN KEY "fk_lvuad_pid"`

The correct syntax IN POSTGRESQL : 
`ALTER TABLE "users_address" DROP CONSTRAINT IF EXISTS  "fk_lvuad_pid"`;

Thank you

**Comment by aimeos** [comment]
Fixed in dev-master and 2021.04.x-dev
