### ISSUE TITLE
" FOREIGN KEY" is not allowed in  POSTGRESQL

### ISSUE THREAD

**Issue by MahmoudDevo** [aimeos/aimeos-core#225]
Hello,
Error:
```
 C:\laragon\www\devoshop_v8.7\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\Setup\Task\Base.php:146
      Aimeos\MW\DB\Statement\DBAL\Simple::execute()

  2   C:\laragon\www\devoshop_v8.7\ext\ai-laravel\lib\custom\setup\CustomerRemoveConstraints.php:70
      Aimeos\MW\Setup\Task\Base::execute("ALTER TABLE "users_list" DROP FOREIGN KEY "fk_lvuli_pid"", "db-customer")  
```

in the file: 
**C:\laragon\www\devoshop_v8.7\ext\ai-laravel\lib\custom\setup\CustomerRemoveConstraints.php**
C:\laragon\www\devoshop_v8.7\ext\ai-laravel\lib\custom\setup\CustomerRemoveConstraints.php

`ALTER TABLE "users_list" DROP FOREIGN KEY "fk_lvuli_pid"`

C:\laragon\www\devoshop_v8.7\ext\ai-laravel\lib\custom\setup\CustomerRemoveConstraints.php:83
 ALTER TABLE "users_property" DROP FOREIGN KEY "fk_lvupr_pid

The correct syntax In POSTGRESQL : 
`ALTER TABLE "users_address" DROP CONSTRAINT IF EXISTS   "fk_lvuad_pid"`;

Thank you

**Comment by aimeos** [comment]
Fixed in dev-master and 2021.04.x-dev
