### ISSUE TITLE
ERROR/  drop index mshop_locale_site_siteid_key

### ISSUE THREAD

**Issue by MahmoudDevo** [aimeos/aimeos-core#226]
Hello,
ERROR  UPGRADE from 2020.10 to 2021.04 in PostgreSQL.
AFTER. p`hp ./artisan aimeos:setup`
![ERROR3](https://user-images.githubusercontent.com/7951825/115640492-9af7e280-a306-11eb-96f3-581a5e49c2ae.png)

**Comment by aimeos** [comment]
Same as #227
