### ISSUE TITLE
Catalog New : Error

### ISSUE THREAD

**Issue by MahmoudDevo** [aimeos/aimeos-core#230]
Hi;
PostgreSQL 9.6.15
Laravel Framework 8.37.0
PHP 7.4.16
"php": "^7.3|^8.0",
"aimeos/aimeos-laravel": "~2021.04",
**The categories are not displayed in the admin part;
if i add a category it displays an error in the homepage** 
![error_catalog](https://user-images.githubusercontent.com/7951825/116018210-16bc9c80-a631-11eb-8e65-07f99332a2af.png)

**Comment by aimeos** [comment]
Please check the browser console if there's a JS error or the server doesn't respond with a 200 code.

**Comment by MahmoudDevo** [comment]
Thank you 👍  ,
the error because in my extension,  not available class **mynewdatadomain**
ext\devoext\config\admin.php

return [
	'jqadm' => [
		
	],
	'jsonadm' => [
		'domains' => [
            'mynewdatadomain' => 'mynewdatadomain'
        ],
        'resources' => [
            'mynewdatadomain/config' => 'mynewdatadomain/config'
        ],
	],
];
thank you
