### ISSUE TITLE
updateStockSelection is not working properly

### ISSUE THREAD

**Issue by switch-cheehau** [aimeos/aimeos-core#240]
Hi Aimeos, 

Need confirmation from you
Setup:
- Create a selection <code>product A</code> with variant <code>A1</code> and <code>A2</code>
- Make a purchase <code>A1</code>

The information stored in mshop_order_base_product
- column.prodid -- <code>product A</code> instead of <code>A1</code>
- column.code -- <code>A1</code>
Is it a bug?

If it's not a bug, the function updateStockSelection is having issue because it won't update the <code>A1</code> stocklevel due to wrong <code>prodid</code>.

**Comment by aimeos** [comment]
It's intended because we need a reference to the selection product as well as the variant article.

**Comment by switch-cheehau** [comment]
Hi Aimeos, 

Sorry, please ignore my previous PR. I've figured out the original coding logic.

I think this line is causing issue for selection product
https://github.com/aimeos/aimeos-core/blob/ebf17e5c191f9dad64f8e146d688a542d94d9712/controller/common/src/Controller/Common/Order/Standard.php#L350

it should be 

if( $item->getType()=='select' ) {
&nbsp;&nbsp;&nbsp;&nbsp;$stockManager->decrease( [$item->getProductVariantId() => $how * -1 * $item->getQuantity()], $item->getStockType() );
} else {
&nbsp;&nbsp;&nbsp;&nbsp;$stockManager->decrease( [$item->getProductId() => $how * -1 * $item->getQuantity()], $item->getStockType() );
}

Let me know what you think

**Comment by aimeos** [comment]
Yes, that looks better and you can write it shorter:
```php
$prodId = $item->getType()=='select' ? $this->getArticleId( $item->getProductId(), $item->getProductCode() ) : $item->getProductId();
$stockManager->decrease( [$prodId => $how * -1 * $item->getQuantity()], $item->getStockType() );
```

**Comment by aimeos** [comment]
Fixed in https://github.com/aimeos/aimeos-core/commit/e2b1191bdcd74e0e9b0fb51de978de121b852d5e
