### ISSUE TITLE
Payment service does not sort based on position field for Frontend

### ISSUE THREAD

**Issue by switch-cheehau** [aimeos/aimeos-core#244]
Hi Aimeos,

I tried to set position for payment service. 
![image](https://user-images.githubusercontent.com/82187386/125476668-c2a1d790-a813-45ec-bbaf-3f67b5b14a72.png)

It only works in Admin page, but it does not work in Frontend. Is it intended?

I tried to add following changes before line 681 and it works. Is it correct?
```
$search->setSortations( [$search->sort( '+', 'service.type' ), $search->sort( '+', 'service.position' )] );
```

https://github.com/aimeos/aimeos-core/blob/7f2f6bcffe5afcb206fb708180094b53f34324ed/lib/mshoplib/src/MShop/Service/Manager/Standard.php#L681

**Comment by aimeos** [comment]
That has been fixed two month ago: https://github.com/aimeos/ai-controller-frontend/commit/c8f6f51ee938f4df861dae5d440c64e19f9eaedb

Which Aimeos version are you using?

**Comment by switch-cheehau** [comment]
oh, i see, i'm still using 2021-04.
because recently trying to launch a new website for that. haven't got time to update it.
