### ISSUE TITLE
Columns not found after composer update from 2021.04 -> 2021.07

### ISSUE THREAD

**Issue by zherdev-artem** [aimeos/aimeos-core#246]
Hi, after the composer update 2021.04 -> 2021.07 the error of column is not found shows up, artisan aimeos:setup such as any other command doesn't work with the same error.

``` Aimeos\MW\DB\Exception  : SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mlocsi.icon' in 'field list' ```

**Comment by aimeos** [comment]
Can you please post the output of the setup process and the stack trace of the exception?

**Comment by zherdev-artem** [comment]
Unfortunately, I can't give a stack trace now, it is wasn't a setup process just as an update from 04 to 07. After composer update and getting errors with column unknown, I have updated missed fields by hand and of course, the problem has gone. After I had an error about unavailable DB connection resource in shop config, I copy-paste it from aimeos-core default and all worked.

I think after a couple of days I will do the same on our stage server and could store trace info if it will happen again.

**Comment by aimeos** [comment]
Seems like you've executed an own command (App\\Console\\Commands\\UpdateCodes) before running the `aimeos:setup` command (e.g from the composer scripts section).

**Comment by zherdev-artem** [comment]
Yes I missed log about own command, and seems it because php artisan package:discover iterate all laravel commands, and exactly in UpdateCodes in construct was ```$this->context = app('aimeos.context')->get();```, and seems it a culprit.

Thank you!
