### ISSUE TITLE
Tree\Manager\DBNestedSet::getNodeById() 

### ISSUE THREAD

**Issue by flobee** [aimeos/aimeos-core#256]
the example 'get' statement for `getNodeById()` seems to be too expensive. the id is always known and therefore a simple select statement by id improves the execution time when introducing "get one": 'getone'.
Or do i miss any functionality which can be used where this query counts?

DBNestedSet manager inline docs:
```
[get] =>
    SELECT node.*
    FROM treetable AS parent, treetable AS node
    WHERE node.left >= parent.left AND node.left <= parent.right
    AND parent.id = ? AND node.level <= parent.level + ?
    AND type = <type> AND :cond
    ORDER BY node.left
```

**Comment by aimeos** [comment]
`id LIKE ?` won't work and doesn't return the levels below the given ID if required. Depending on the actual usage in Aimeos it could be a good idea to add a single SQL statement with `id = ?` for retrieving the current node only if that is most often used
