### ISSUE TITLE
Setup error for PostgreSQL

### ISSUE THREAD

**Issue by MahmoudDevo** [aimeos/aimeos-core#261]
Hi,
I use :
P**ostgreSQL 12
Laravel Framework 8.37.0
PHP 7.4.16**

"php": "^7.3|^8.0",
"aimeos/ai-cms-grapesjs": "~2021.07",
        "aimeos/aimeos-laravel": "~2021.07",
 

After : `php artisan aimeos:setup`

Display : 
 
`Aimeos\MW\DB\Exception 

  SQLSTATE[23502]: Not null violation: 7 ERROR:  column "instock" contains null values: ALTER TABLE mshop_product ADD instock SMALLINT NOT NULL        

  at C:\laragon\www\site\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\DB\Statement\DBAL\Simple.php:75
     71▕        {
     72▕                try {
     73▕                        $result = $this->exec();
     74▕                } catch( \PDOException $e ) {
  ➜  75▕                        throw new \Aimeos\MW\DB\Exception( $e->getMessage() . ': ' . $this->sql, $e->getCode() );
     76▕                }
     77▕
     78▕                return new \Aimeos\MW\DB\Result\PDO( $result );
     79▕        }

  1   C:\laragon\www\site\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\Setup\Task\Base.php:164
      Aimeos\MW\DB\Statement\DBAL\Simple::execute()

  2   C:\laragon\www\site\vendor\aimeos\aimeos-core\lib\mshoplib\setup\TablesCreateMShop.php:177
      Aimeos\MW\Setup\Task\Base::executeList("db-product")`
 
Thank you

**Comment by MahmoudDevo** [comment]
Hello,
Please change : `$table->addColumn( 'instock', 'smallint', [] );`
to `$table->addColumn( 'instock', 'smallint', ['default' => 1] );`
thank you

**Comment by aimeos** [comment]
Thank you for the hint!
A default value has been added and the change is available in 2021.10.x-dev:
```
composer req aimeos/aimeos-core 2021.10.x-dev
```
