### ISSUE TITLE
PayPalExpress response: Invalid total

### ISSUE THREAD

**Issue by jonaseberle** [aimeos/aimeos-core#270]
It seems PayPal has gotten more strict in the last week or so.

https://github.com/aimeos/aimeos-core/blob/94d09cacf6e7973916d9b23c2e75ccca33152712/lib/mshoplib/src/MShop/Service/Provider/Payment/PayPalExpress.php#L751-L754

can result in 
```json
"MAXAMT":221.75,
"PAYMENTREQUEST_0_AMT":"221.74",
"PAYMENTREQUEST_0_ITEMAMT":"214.01",
"PAYMENTREQUEST_0_SHIPPINGAMT":"7.74",
```

It seems that earlier individual items were not checked and the `MAXAMT` field was fine for rounding errors in the total.

We get "Total mismatch. See additional message for details. / The totals of the cart item amounts do not match order amounts." back from PayPalExpress now.

**Comment by nvindice** [comment]
Can you provide a full list of all parameters used for the invalid query including all items, services, etc?

**Comment by jonaseberle** [comment]
This is without any manual changes.
```
  ["L_PAYMENTREQUEST_0_NUMBER0"]=>
  string(3) "279"
  ["L_PAYMENTREQUEST_0_NAME0"]=>
  string(29) "Stabilizer fitting, snap lock"
  ["L_PAYMENTREQUEST_0_QTY0"]=>
  float(1)
  ["L_PAYMENTREQUEST_0_AMT0"]=>
  string(6) "214.01"
  ["L_SHIPPINGOPTIONAMOUNT0"]=>
  string(4) "0.00"
  ["L_SHIPPINGOPTIONLABEL0"]=>
  string(13) "Sendcloud-UPS"
  ["L_SHIPPINGOPTIONNAME0"]=>
  string(3) "UPS"
  ["L_SHIPPINGOPTIONISDEFAULT0"]=>
  string(4) "true"
  ["MAXAMT"]=>
  float(221.75)
  ["PAYMENTREQUEST_0_AMT"]=>
  string(6) "221.74"
  ["PAYMENTREQUEST_0_ITEMAMT"]=>
  string(6) "214.01"
  ["PAYMENTREQUEST_0_SHIPPINGAMT"]=>
  string(4) "7.74"
  ["PAYMENTREQUEST_0_INSURANCEAMT"]=>
  string(4) "0.00"
  ["PAYMENTREQUEST_0_INSURANCEOPTIONOFFERED"]=>
  string(5) "false"
  ["PAYMENTREQUEST_0_SHIPDISCAMT"]=>
  string(4) "0.00"
  ["PAYMENTREQUEST_0_CURRENCYCODE"]=>
  string(3) "EUR"
  ["PAYMENTREQUEST_0_PAYMENTACTION"]=>
  string(4) "Sale"
  ["METHOD"]=>
  string(18) "SetExpressCheckout"
```
In order to fix #269 ("Invalid Shipping Total"), I would manually set 
`'L_SHIPPINGOPTIONAMOUNT0' => '7.74',`

In order to make PayPal accept it, I would manually set 
`'PAYMENTREQUEST_0_AMT'] = '221.75'`

That small rounding problem seems to annoy PayPal (now). I understand from the aimeos code that it expects `MAXAMT` to cater for rounding errors. But in PayPal's docs https://developer.paypal.com/docs/nvp-soap-api/set-express-checkout-nvp/ they don't explicitly mention that.

I have this rounding error on the order summary as well:
![image](https://user-images.githubusercontent.com/1678001/144469233-14f973ef-8bbf-40a6-91eb-004c070b736f.png)

**Comment by jonaseberle** [comment]
A workaround is of course to not send shipping/basket information at all:
```
paypalexpress.product=false
paypalexpress.service=false
```

I think finally it boils down to having `\Aimeos\MShop\Order\Item\Base\Standard::getPrice()` round each line to the configured precission before summing. I am not sure if that would be a feasible change for Aimeos?

**Comment by aimeos** [comment]
Why is there a rounding error at all? Do you calculate the product price of `214.01` and the shipping costs of `7.74` yourself, maybe during VAT calculation?

**Comment by jonaseberle** [comment]
I am setting tax rates `$orderService->getPrice()->setTaxrate($taxrate);` on service item price items.

**Comment by nvindice** [comment]
Not sure where this rounding error comes from, though. The prices are added here: https://github.com/aimeos/aimeos-core/blob/86ec39902cd80b5dc9c88d0354a0fb49713386bf/lib/mshoplib/src/MShop/Price/Item/Standard.php#L402

Do you use `precision = 2` in all cases? IMO this should make a rounding error impossible.

**Comment by jonaseberle** [comment]
Sorry for the long delay.

I don't add up anything manually. I just use `(\Aimeos\MShop\Order\Item\Base\Service\Iface)->getPrice()->setTaxrate($taxrate)`.


The adding is probably coming from here, isn't it?

https://github.com/aimeos/aimeos-core/blob/94d09cacf6e7973916d9b23c2e75ccca33152712/lib/mshoplib/src/MShop/Service/Provider/Base.php#L319-L344

**Comment by aimeos** [comment]
Depending on the tax rate, this could create a rounding problem. If the calculated tax value is x.xx5, both the tax value and the shipping amount would be rounded up in the PayPal provider. Internally, tax values are stored with four decimal digits.

**Comment by jonaseberle** [comment]
If that four digits is important for Aimeos, I don't see how I could solve it then by default means.

I think my best bet is reimplementing either `\Aimeos\MShop\Price\Item\Standard::getTaxValue()` or `\Aimeos\MShop\Price\Item\Standard::setTaxValue` and use 2 digits only.

Thanks for your help anyways.

**Comment by aimeos** [comment]
We think the problem is in that line:
https://github.com/aimeos/aimeos-core/blob/94d09cacf6e7973916d9b23c2e75ccca33152712/lib/mshoplib/src/MShop/Service/Provider/Payment/PayPalExpress.php#L748

If you remove the "+ 2" at the end, does it work then?

**Comment by jonaseberle** [comment]
Yes, that's what I wanted to say ;)

**Comment by aimeos** [comment]
If that fixes the problem, can you create a PR we can merge?

**Comment by jonaseberle** [comment]
Sorry, I currently don't have an aimeos-master (or 2021 for that matter) with data and it's a bit hard to test for me.

**Comment by jonaseberle** [comment]
Oh, and there was a misunderstanding regarding your question. I would adapt `\Aimeos\MShop\Price\Item\Standard::getTaxValue` / `\Aimeos\MShop\Price\Item\Standard::setTaxValue` and remove the "4 digits for taxes" completely. 

Do you remember why it was implemented like that?

**Comment by aimeos** [comment]
We can't remove the four digits for taxes completely because then you have an even bigger rounding error the higher the ordered product quantities are. The correct solution should be to remove the `+ 2` from that line only: https://github.com/aimeos/aimeos-core/blob/94d09cacf6e7973916d9b23c2e75ccca33152712/lib/mshoplib/src/MShop/Service/Provider/Payment/PayPalExpress.php#L748

**Comment by aimeos** [comment]
The `+2` has been removed now in dev-master, 2021.10.x-dev and 2020.10.x-dev
Does it work now in your setup?

**Comment by jonaseberle** [comment]
I think that fixes that part. It should be done in https://github.com/aimeos/aimeos-core/blob/8a5e18e91edf6365019ad9924501b19d67911f20/lib/mshoplib/src/MShop/Service/Provider/Payment/PayPalExpress.php#L744 as well IMHO.
