### ISSUE TITLE
Hourly subscription does not work after shop update

### ISSUE THREAD

**Issue by sruhani** [aimeos/aimeos-core#279]
https://github.com/aimeos/aimeos-core/blob/0a217be5f444111eeb2908552d186a451375598c/lib/mshoplib/src/MShop/Subscription/Item/Standard.php#L164

Stündliche Subscription funktionieren nicht, tägliche aber schon, nur bei den stündlichen ist der Prefix "PT" und nicht nur "P". Ist hier ein Bug?

**Comment by aimeos** [comment]
This has been fixed an hour ago:
https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/src/MShop/Subscription/Item/Standard.php#L164
