### ISSUE TITLE
How to use aimeos-laravel folder files in extension to overside custom theme

### ISSUE THREAD

**Issue by rahulhhb** [aimeos/aimeos-core#281]
I have created a extension but there is no details given about how to overwrite following directory. vendor\aimeos\aimeos-laravel
i want to use custom code for this with the help of extension... please guide where to place these files in extensions and how to update the dependency in composer.

**Comment by aimeos** [comment]
Please ask in the Aimeos forum for help because Github issues are only meant for bugs.
