### ISSUE TITLE
Price quantity decimal

### ISSUE THREAD

**Issue by exemplari** [aimeos/aimeos-core#284]
**Environment**
1. Version (e.g. 2017.10)
"aimeos/aimeos-laravel": "2021.10.*",

**Describe the bug**
Quantity is saved to database as integer.

**To Reproduce**
1. Go to Admin > Product Item
2. Click on Price
3. Add a price with a decimal Quantity. Eg) 0.5
4. Save.

**Expected behavior**
I expect the quantity to be 0.5 
The quantity is 0.

**Additional context**
Quantity is a float in the UI. A float in the controller. But an integer when bind to database.

\Aimeos\MShop\Price\Manager\Standard. Line 495

`$stmt->bind( $idx++, $item->getQuantity(), \Aimeos\MW\DB\Statement\Base::PARAM_INT );`

to

`$stmt->bind( $idx++, $item->getQuantity() );`

**Comment by aimeos** [comment]
Thanks, it should be:
```
$stmt->bind( $idx++, $item->getQuantity(), \Aimeos\MW\DB\Statement\Base::PARAM_FLOAT );
```
Can your create a PR?
