### ISSUE TITLE
Error after setup  

### ISSUE THREAD

**Issue by MahmoudDevo** [aimeos/aimeos-core#292]
`Hi,
I use :
PostgreSQL 14
"laravel/framework": "^9.2",
 

  "php": "^7.3|^8.0",
        "aimeos/aimeos-laravel": "~2022.04",
        "aimeos/ai-cms-grapesjs": "2022.04.1",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^9.2",
        "laravel/jetstream": "^2.2",
        "laravel/sanctum": "^2.6",
        "laravel/tinker": "^2.5",
        "livewire/livewire": "^2.0",
        "phing/phing": "^2.16"`

After run: 
`php artisan aimeos:setup `
Clear property "key" columns

In Table.php line 895:

  Undefined array key "engine"  
https://github.com/aimeos/aimeos-core/blob/7b5f5c0d171d4e43eb2ce3b3ae4deb4b649783fd/setup/IndexMigrateTextInnodb.php#L30

**Comment by aimeos** [comment]
Fixed in `aimeos/upscheme` 0.8.1+. Please update `aimeos/aimeos-core` too because we've discovered a bug in Doctrine DBAL and added a workaround for that.
