### ISSUE TITLE
Retrieving custom config values for sub-sites

### ISSUE THREAD

**Issue by defive** [aimeos/aimeos-core#296]
I am trying to retrieve the config value for 

```
controller/jobs/product/import/csv/location
```

from within an admin panel, but using 

```
$view->config('controller/jobs/product/import/csv/location', false); 
```

returns false. If I set the value in shop.php then the value set there is retrieved rather than the config override set in locales > sites > subsite.

Should the config helper return overridden values or is there another function to do this?

**Comment by aimeos** [comment]
The config view helper should return overwritten values by the site.
Can you post a screenshot from the sites config table for that setting?

**Comment by defive** [comment]
![Screenshot from 2022-08-17 12-28-54](https://user-images.githubusercontent.com/13240380/185123571-f6a5729e-485e-4b12-b944-36e9f0b3f5b4.png)

I can see the data in the mshop_locale_sites table in the database too, but the method $view->config() does not return anything for any of these values unless they are set in shop.php and then the value from shop.php is returned and not the overridden value.

**Comment by aimeos** [comment]
In theory it should work because the config from the site item is applied to the config object here:
https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/Command/AbstractCommand.php#L65

Can you check if the key is available after that line, please?

**Comment by defive** [comment]
Okay, I added the following line on line 66 of that file:

```
file_put_contents('/tmp/testing.txt', print_r($config, true));
```

Then ran the following line from within the sub-site admin pages

```
$view->config('controller/jobs/product/import/csv/location', false); 
```

I checked the testing.txt file and found none of the sub-sites config settings were there.

**Comment by aimeos** [comment]
Can you check if `$config->get( 'controller/jobs/product/import/csv/location' )` in line 66 returns something?

**Comment by defive** [comment]
I have added that to my file_put_contents line and the result is an empty file so it's definitely not returning anything

```
file_put_contents('/tmp/testing.txt',  $config->get( 'controller/jobs/product/import/csv/location' ));
```

**Comment by aimeos** [comment]
Does `$siteItem->getConfig()` returns the configuration you want?

**Comment by defive** [comment]
No, that returns an empty array

**Comment by aimeos** [comment]
Then, you are using a different site which doesn't contain the mentioned configuration settings. You can specify the site for the job as last parameter: `php artisan aimeos:jobs product/import/csv h-and-r-clothing-store`

**Comment by defive** [comment]
I'm not running the job yet. This code is being run on an admin panel where I want to check whether a CSV file is uploaded for this site. I'm viewing the page/panel on the h-and-r-clothing-store sub-site and have checked that the config setting is set on the h-and-r-clothing-store sub-site locale page but I cannot see any of the custom config items, only what is set in the main shop.php file.

Even if I browse to the main store and view my panel I can't get it to retrieve any custom config items from the main store. i.e. changing the background color on the locale > sites page is not shown if I retrieve it using $view->config();

**Comment by aimeos** [comment]
This doesn't work in the admin backend yet because the site config isn't applied to the config item of the context here:
https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/Controller/JqadmController.php#L257-L259

If you can create a PR, we will merge it.

**Comment by defive** [comment]
I see, that makes sense! I'll take a look and see if I can add it
