### ISSUE TITLE
Problem with submanager name

### ISSUE THREAD

**Issue by matteovg7** [aimeos/aimeos-core#300]
Hi,
from version 2022.07.7 I have again the problem with submanager names that was fixed in version 2022.07.6 with this pull request: https://github.com/aimeos/aimeos-core/pull/297

If the structure of config file is changed in this new version and I need to change the structure of config file to a new format please tell me how.

Thank you!

**Comment by aimeos** [comment]
Please see: https://github.com/aimeos/aimeos-core/pull/297#issuecomment-1339037750
