### ISSUE TITLE
IBAN gets masked with DirectDebit

### ISSUE THREAD

**Issue by codemonkey1988** [aimeos/aimeos-core#301]
**Aimeos Version:** 2021.10.23 (its not latest uf 2021.10, but as far as I can see, 2021.10.25 contains the same bug)

**Description**
There is a bug, that leading to the loss of the IBAN information for an order payed with DirectDebit. The IBAN will get masked in completly, so that even in the Aimeos Backend, there is no clear text IBAN.

**Steps to reproduce**
Starting with the payment step in the checkout process:

1. Choose DirectDebit as Payment method and enter the IBAN
2. Proceed to the Summary Step
3. Go back to the payment step - now the IBAN field value is the masked value
4. Proceed to summary and submit order

The now generated order will have no clear IBAN submitted. This is because the DirectDebit Service provider will replace the attribute value for the original IBAN with the masked one and create a new hidden attribute with the clear value. When going back to payment, the System will work with the non hidden IBAN attribute value, which is masked by now. When there is no IBAN check and the customer will not notice the change (or thinks that the XXXXX IBAN value is correct, because it is learned behavior) the customer will submit the order with an invalid (masked) IBAN.

**Comment by codemonkey1988** [comment]
Yes, that is correct.

**Comment by aimeos** [comment]
Can you please check why that line doesn't display the unmasked value as intended?
https://github.com/aimeos/ai-client-html/blob/master/src/Client/Html/Checkout/Standard/Payment/Standard.php#L150

**Comment by codemonkey1988** [comment]
I've debugged the line you send me. It seems that the the `getAttribute()` method is called with false arguments. It should be 
`$item->value = $oservice->getAttribute( $key, 'payment/hidden' ) ` because that Type is `payment/hidden`. If I call the method as I said, it works.

**Comment by aimeos** [comment]
OK, can you create a PR with the fix?

**Comment by codemonkey1988** [comment]
Yes, I can do that.
