### ISSUE TITLE
jsonapi/customer returns 404 with filled "mshop/customer/manager/name" setting.

### ISSUE THREAD

**Issue by Tantacula** [aimeos/aimeos-core#303]
I've tried to add my own customer manager to mshop.php:

```php
    'customer' => [
        'manager' => [
            'name' => 'Manager'
        ],
    ],
```
but api method jsonapi/customer returns error" 404: Item with ID "8" in "customer.id" not found" with this setting.

This error also appears if I set default "Standard" name (file Standard.php not exists in my theme)

```php
    'customer' => [
        'manager' => [
            'name' => 'Standard'
        ],
    ],
```

php 8
Laravel v9.52.1
"aimeos/aimeos-core": "2022.10.x-dev",
"aimeos/aimeos-laravel": "~2022.10",

**Comment by aimeos** [comment]
Is the customer with ID "8" in the `users` table assigned to the site (-> `users.siteid`) you are trying to fetch?

**Comment by Tantacula** [comment]
No. I added "1." to siteid field now and nothing changed.

**Comment by aimeos** [comment]
If it was empty before, this means that the customer is available in all sites.

Change logging in `config/shop.php` to `7` so all SQL queries are logged and check the query for the mshop_customer table why it returns no record.

**Comment by Tantacula** [comment]
The problem that is without this option query uses "users" table (Laravel default table) and with this option table changes to mshop_customer which is empty.

**Comment by Tantacula** [comment]
I think problem is solved now, I should extend Laravel manager instead Standard Aimeos manager.
