### ISSUE TITLE
Manager name question

### ISSUE THREAD

**Issue by Tantacula** [aimeos/aimeos-core#304]
When I set "mshop/customer/manager/name" option to Mymanager this also affects on submanagers names. For example following code in file aimeos-laravel/src/Aimeos/Shop/Base/Support.php:

```php
\Aimeos\MShop::create( $context, 'customer/group' );
```
throws an error:
```php
Class "\Aimeos\MShop\Customer\Manager\Group\Mymanager" not available
```

Is this expected behavior and I should write all manager names manually or this is a bug?

**Comment by aimeos** [comment]
The behavior changed when moving to the central `MShop::create()` factory. We can't revert it in the current LTS version but will do so in the upcoming 2023.x versions.

In the meantime, you have to configure the managers you don't want to change manually, e.g.
```
mshop/customer/manager/group/name = Standard
```
