### ISSUE TITLE
Remove fields from billing form

### ISSUE THREAD

**Issue by Michael-0208** [aimeos/aimeos-core#307]
Hi everyone,

How can I remove fields from the billing form in aimeos v2022.10? 

There is no extra configuration in `config/shop.php` I want to remove some fields from the billing form, I even tried to check in the admin panel but can't see any option to modify my billing page. Please Help!

Regards, 
Vikash

**Comment by aimeos** [comment]
Please use the Aimeos forum for support questions:
https://aimeos.org/help
