### ISSUE TITLE
To create a customer account

### ISSUE THREAD

**Issue by NellitG** [aimeos/aimeos-core#312]
How can I create a customer account in that the customer can log in?

**Comment by aimeos** [comment]
```
$manager = \Aimeos\MShop::create( $context, 'customer' );
$item = $manager->create()->setCode( 'me@domain.tld' )->setPassword( 'secret' );
$manager->save( $item );
```

Please ask questions in the Aimeos forum (https://aimeos.org/help) as Github issues are only for bug fixes and feature request.
