### ISSUE TITLE
default wrong locale for new sites

### ISSUE THREAD

**Issue by wladimiravila** [aimeos/aimeos-core#316]
Hi everyone, I'm having a problem when trying to create a new shop with a specific template for setup like this:

\Aimeos\Setup::use(new \Aimeos\Bootstrap())->context($context)->verbose('vv')->up($code, 'my_custom_template');

It doesn't matter my data code, for all new shops are the setup _EUR_ and _en_  language

https://github.com/aimeos/aimeos-core/blob/master/setup/MShopAddLocaleData.php#L64

This is a problem because not all new shops  aren in EUR neither _en_ language , and if the request doesn't match it, the portal throws an error.

The custom template creation feature should allow the developer to customize all data entered into the database for new shops.

Could be necessary to create a data class inside de setup/default folder

Regards

WladimirAvila

**Comment by aimeos** [comment]
We've removed adding that default locale as it shouldn't be necessary in any way. You can get the latest code by executing `composer req aimeos/aimeos-core:2024.04.x-dev`
