### ISSUE TITLE
[FEATURE] Rename HTML template files to php

### ISSUE THREAD

**Issue by ste101** [aimeos/aimeos-core#44]
The HTML files below client/html are php files so syntax coloring is not correct.

Would it be possible to rename theses files?

Regards
Stephan

**Comment by aimeos** [comment]
Yes, that would be feasible. We are currently changing all things that we are not happy with because the next release is one of the few that don't have to be backward compatible. We will care about that.

**Comment by aimeos** [comment]
The template files have been renamed and are moved the directory "templates" instead of "layouts". The changes will be part of the next stable release (scheduled for January).
