### ISSUE TITLE
 Class 'Aimeos\MW\Setup\Task\MShopAddLocaleData' not found

### ISSUE THREAD

**Issue by jojouser** [aimeos/aimeos-core#46]
I have installed a demo neos2.0.3version+ aimeos; when i try to create  tables and to add the demo data
#./flow aimeos:setup --option=setup/default/demo:1
It show this message:
PHP Fatal error:  Class '\MW\Setup\Task\MShopAddLocaleData' not found in /public_html/test/Neos-2.0/Packages/Libraries/aimeos/aimeos-core/lib/mshoplib/setup/MShopAddLocaleLangCurData.php on line 16

**Comment by aimeos** [comment]
Tried myself but I didn't get the error - but that doesn't mean it works in all cases.
Could you please replace in
`Packages/Application/Aimeos.Shop/Classes/Aimeos/Shop/Command/AimeosCommandController.php`
in the `autoload()` method (line 168) `'MW_Setup_Task_'` by
`'Aimeos\\MW\\Setup\\Task\\'` or
`'\\Aimeos\\MW\\Setup\\Task\\'`?
Then execute `./flow aimeos:setup` again

**Comment by aimeos** [comment]
Any news on this?

**Comment by jojouser** [comment]
I still have the same problem. I will try to install a new demo on another server.

**Comment by antoniputra** [comment]
I have same issue in laravel 5.2.
and I don't have idea how to fix this.

any suggestion ?

**Comment by aimeos** [comment]
Can you change the "aimeos/aimeos-laravel" requirement in your `composer.json to "dev-master", call `composer update` and try again, please?

**Comment by antoniputra** [comment]
after change version to `dev-master`

I've got this : 
![aimeos-error](https://cloud.githubusercontent.com/assets/3622084/13904858/e01568cc-eee0-11e5-84b4-abb593eb44d0.png)

**Comment by aimeos** [comment]
Seems to me like you've forgot these lines in your `composer.json`:
```
    "prefer-stable": true,
    "minimum-stability": "dev",
```
See https://github.com/aimeos/aimeos-laravel#installation-or-update for the full documentation.

**Comment by antoniputra** [comment]
awesome :+1: 
works like charm right now..

just have next problem for authentication into admin page, after follow all insttruction on your given link. then fill login form and submit it on `http://127.0.0.1:8000/index.php/admin`, always got `NotFoundHttpException`.

**Comment by aimeoscom** [comment]
That depends on Laravel authentication configuration and on the Laravel version. Please ask in the forum (https://aimeos.org/help/) for details.
