### ISSUE TITLE
In object \Aimeos\MW\View\Standart, method resolve has problem.

### ISSUE THREAD

**Issue by jooorooo** [aimeos/aimeos-core#59]
In object \Aimeos\MW\View\Standart, method resolve has problem.

line 242: 
if( strncmp( $file, '/', 1 ) === 0 && is_file( $file ) ) { 

must be 

if( strncmp( $file, '/', 1 ) === 0 || is_file( $file ) ) {

**Comment by aimeos** [comment]
Does testing for a leading slash make problems in WAMP environments?

**Comment by aimeos** [comment]
Fixed in c9ebdb7 of dev-master
