### ISSUE TITLE
ERM version

### ISSUE THREAD

**Issue by earosb** [aimeos/aimeos-core#76]
![aimeos-core-erm](https://cloud.githubusercontent.com/assets/4139822/16774302/6a02ad50-4829-11e6-894a-37baf70bab02.png)
I recently downloaded this erm from aimeos docs, but is not the same i have in my installation 

- typo3 7.6.9
- aimeos 16.4.3
- aimeos_dist	16.4.0

**Comment by aimeos** [comment]
It's not totally up to date, e.g. the index stuff has been separated from the catalog domain and the tag tables have been moved out of the product domain. The rest is more or less the same. We will update the ERM diagram before we release the 2016 LTS version in October.

**Comment by aimeos** [comment]
Here's the latest version:
https://aimeos.org/fileadmin/download/Aimeos-database.svgz
