### ISSUE TITLE
[BUG] use statements (maybe also other classes) not recognized during syncUpdate of payments

### ISSUE THREAD

**Issue by AndreasA** [aimeos/aimeos-core#78]
I am not sure why but trying to access other classes if the have been included with "use" doesn't work during syncUpdate of a Payment provider.
It seems to work fine otherwise though.
I am not even sure it works all the time with the fully qualified classname there.
Probably somehow related to how the updateSync method is called?

**Comment by aimeos** [comment]
Do you have example code to reproduce the problem

**Comment by AndreasA** [comment]
Strangley I can't reproduce the error anymore.
If I encounter it again I will let you know, i am closing the issue for now.
