### ISSUE TITLE
[BUG] ProductPrice changed message on summary page repeats endlessly

### ISSUE THREAD

**Issue by AndreasA** [aimeos/aimeos-core#79]
If you get the ProductPrice changes message on the summary page, another submit just displays the error again but nothing further happens.
First encountered this in combination with ai-customergroups extension.

Going back to the basket and re-sbumitting restarting the checkout process, however, works correctly.

**Comment by aimeos** [comment]
The ProductPrice basket plugin seems to check for the wrong price in this case. We will have a look.

**Comment by nos3** [comment]
We've fixed the problem but it requires an matching version of the Aimeos core too as well as a configuration change (see Readme.md). Currently, the changes are only in the dev-master version and I will drop you a note as soon as new stable version are released.

**Comment by aimeos** [comment]
A new stable version of the Aimeos core has been released

**Comment by AndreasA** [comment]
The decorators for Basket and service are not requried anymore but catalog is?

**Comment by nos3** [comment]
Yes and don't forget the "excludes" for the locale site manager
