### ISSUE TITLE
[BUG] details of small basket not updated on adding product

### ISSUE THREAD

**Issue by AndreasA** [aimeos/aimeos-core#80]
I am not sure if this is ai-typo3 or aimeos-core but when adding a product to the basket, the quantity in the label itself is updated but the details are not, they require a page reload, this can be testet here:
http://typo3.demo.aimeos.org/performance

I think the click on the arrow should instead of just opening the information do an ajax request which provides the infromation / html.

**Comment by aimeos** [comment]
The update is done by Javacript when the basket overlay is displayed. We can update the mini basket details dynamically when the REST JSON API for the frontend is completed.

**Comment by AndreasA** [comment]
So I guess that will be a feature for the 2017.* versions?

**Comment by aimeos** [comment]
Yes, this should be the case

**Comment by aimeos** [comment]
The small basket is now updated using the JSON REST API:
https://github.com/aimeos/ai-client-html/commit/c64c19eef34fa832e560edece73e70dc6b34e2dd
