### ISSUE TITLE
[QUESTION/INFO] PayUnity payment provider

### ISSUE THREAD

**Issue by AndreasA** [aimeos/aimeos-core#81]
I have now finished a payment provider for PayUnity & PayUnity.Flex
Due to PayUnity.Flex using JavaScript forms I decided against omnipay as I also have to modify output in aimeos to support this.

Features that are not in it and I probably won't add as we don't need them are:
option to store payment data on PayUnity server.
Notifications from PayUnity to payment provider.
And also the other way around, e.g. refund to PayUnity from shop system.

I will first have the provider used in our own system for a few weeks to see if everything behaves correctly,
Afterwards I think I will probably make it public.

However, I think adding it to ai-payments or aimeos-core itself might also be a good idea but I don't currently have the time to create the corresponding unittests I would like for that to have first,

So maybe you would be willing to add those and improve the provider accordingly for aimeos-core / ai-payunity code?

**Comment by aimeos** [comment]
If the implementation meets our code quality and it's unit tested, we may add it to the ai-payments extension

**Comment by AndreasA** [comment]
OK. But it might take longer to get the unittests etc. in it.
I will let you know once I have the code far enough, then you can review and let me know about changes that you would like. 
But as mentioned (in another ticket) it might be quite some time until I have the time to finish this.
I will create a separate ticket / PR then.
