### ISSUE TITLE
Change base class attribute visibility

### ISSUE THREAD

**Issue by bruno-rodrigues** [aimeos/aimeos-core#82]
Is there any particular reason for the `private` Base classes' attributes?

I am trying to overwrite `createItemBase` from `Aimeos\MShop\Customer\Manager\Base` to create an extended version of Customer's Item class. 

```
protected function createItemBase( array $values = array(), array $listItems = array(), array $refItems = array() )
    {
        if( !isset( $this->addressManager ) ) {
            $this->addressManager = $this->getSubManager( 'address' );
        }

        $helper = $this->getPasswordHelper();
        $address = $this->addressManager->createItem();

        return new \Aimeos\MShop\Customer\Item\Standard( $address, $values, $listItems, $refItems, $this->salt, $helper );
    }
```

To create a new Item I'll need to access `$this->salt`, which is private.

Can we just change the visibility to `protected`?  This way I would not need to "recalculate" the salt value in my extended class.

**Comment by aimeos** [comment]
"salt" is unused and deprecated. It will be removed in the next months. You can simply pass "null" in your class.

We don't use protected variables in Aimeos for better encapsulation and to avoid them being part of the interface, so they cannot be changed any more without breaking the class interfaces. There are only a few places where we thought we need them to be protected, but we regret that decisions sooner or later.

**Comment by aimeos** [comment]
The "salt" parameter has been removed now. Will be part of the 2017.01 release
