### ISSUE TITLE
Question: js based payment provider with 2017 - howto?

### ISSUE THREAD

**Issue by AndreasA** [aimeos/aimeos-core#84]
Some payment providers include the whole payment credit card form by inserting some hrml code and javascript.
In 2016 version I had to overwrite the whole form by using a decorator but with 2017 this should have been improved.
When updating to 2017 I want to make use of this, so I would like to know how I would do this.

Thanks for answers in advance.

**Comment by aimeos** [comment]
It wasn't possible to break the last form out of the checkout process because there's a dependency between them. The best option for JS based payments is to create a payment provider that returns the target URL and inserts the necessary JS code.

**Comment by AndreasA** [comment]
So modifying the target URL of the form is possible now?
Even if the form doesn't gave any fields?
If ao that should be enough for my payment provider.

**Comment by aimeos** [comment]
Supplying the target URL by a payment service is possible from the beginning.
The only open question is how the JS code must be inserted.

**Comment by AndreasA** [comment]
Hmm. True but didn't that result in a redirect?
Of course adding a dummy field should take care of that.
I guess using a decorator to add the javascript is still the way to go?

**Comment by aimeos** [comment]
If it's a redirect or not can be controlled by the payment service provider.
The decorator is more of a workaround in this case and we would like to offer a cleaner way via the payment service provider. This can be an Omnipay driver too.

**Comment by AndreasA** [comment]
But to add the Javascript directly by using the payment service provider is not yet implemented, is it?
So for now (2017 version) the workaround by using a decorator is required, isn't it?

**Comment by aimeos** [comment]
We need an example what is required to be displayed on the "process" page so we know if it already works or if we have to extend something. Are you able to post your current decorator code?

**Comment by AndreasA** [comment]
Will do some modifications to it to check what I still need with 2017 and then post the decorator, if I still need it.

**Comment by AndreasA** [comment]
OK. Here is what I need to get the JS provider to work correctly:
1.) Add an external script with a parameter provided during payment.
Best would of course be to the header.
2.) Modify form payment URL and add a class to the form (or overwrite form completely)
3.) Modify form content to include IDs of available payment methods, e.g.: VISA MASTER AMEX

From what I can tell this won't work without overriding the form by using a decorator, especially part 3 (and maybe part 1.)?

**Comment by aimeos** [comment]
A decorator is the wrong method in this case.

Instead, add external script to the HTML header of your page (should be no harm to do that on all sites) and create a service provider for the payment gateway:
https://aimeos.org/docs/Developers/Library/Service

In the process() method of the payment service provider, you can define the required input fields, the form URL and method by returning a Form Helper object:
https://aimeos.org/api/latest/class-Aimeos.MShop.Common.Item.Helper.Form.Standard.html

**Comment by AndreasA** [comment]
1.) Cannot add the script to all pages as it requires a unique checkout ID in the URL which is generated during payment initialization.

2.) That solves the URI but I still have to modify the form content completely as it isn't allowed to have ANY fields. It has to a string like: VISA MASTER AMEX and nothing else.
Also in order to avoid displaying that string it would make sense to hide that form at the beginning.
And even better would be to only output it if script is active and otherwise an error.

As mentioned I DO NOT generate the form, the form is completely generated by the payment provider that way I have not issues regarding PCI DSI certification.

3.) I still have to add a class to the form which i also not possible by just modifying the URL.

**Comment by aimeos** [comment]
For 1.) you may also put this into the checkout/standard/process-{body,header}-default.php. This is also the file you should adapt if you need to strip down what's in the form:
https://github.com/aimeos/ai-client-html/blob/master/client/html/templates/checkout/standard/process-body-default.php

Is a specific CSS class required or only one to find the form?

**Comment by AndreasA** [comment]
As far as I know the CSS class only relevant for the JS-Payment provider to find the correct form, it will then be replaced by the payment provider.

In regards to the template that would work.
However, that way one cannot just install the payment provider on another setup and get it wo work without implementing template changes which I would like to avoid.

How about creating a own Form class that extends on the Standard form. Could I somehow capture that form and change the template for that form only, e.g. by modifying the template name if the form is of that instance?
If that isn't possible yet. How about implementing something like that or something similar.

**Comment by aimeos** [comment]
Adding a template might be possible if there's no problem to have a form in a form tag

**Comment by AndreasA** [comment]
That is definitely a problem. 
It isn't even valid in regards to HTML.

Which is why I am using a decorator that way I can completely replace the form with my own code which can be whatever I want / need.

But I think there should be a better solution on how to implement this but I don't think it exists currently. Might require some modifications in aimeos (e.g. 2018 versions)

**Comment by aimeos** [comment]
Can you post the template you would need add for this payment method?

**Comment by aimeos** [comment]
The latest version of the form helper object contains a get/setHtml() method which you should use to paste custom HTML and JS into the form of the process page:

https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/src/MShop/Common/Item/Helper/Form/Iface.php#L89

If your payment provider adds a new form element to that page automatically and you can't suppress it, you have the possibility to modify the DOM using your custom JS.

**Comment by AndreasA** [comment]
@aimeos 
Some open points / questions:

1. I also need to add attributes to the form itself. I guess the best solution would be to just add Javascript with setHtml and let it modify everything accordingly?

1. How do I avoid the automatic redirect of the form? I guess I could add one public field that I hide with CSS as it will be removed by Javascript afterwards anyway?

**Comment by aimeos** [comment]
You can always add fields to the form via your payment service provider:
https://aimeos.org/docs/Developers/Library/Service/Define_configuration#For_the_payment_form

Redirect is only done if you use the HTTP GET method because then no form input is allowed:
- https://github.com/aimeos/ai-client-html/blob/master/client/html/templates/checkout/standard/process-body-standard.php#L198
- https://github.com/aimeos/ai-client-html/blob/master/client/html/themes/aimeos.js#L1400

The changes will be in the next version (2018.07)

**Comment by AndreasA** [comment]
I didn't mean fields like input fields. I know about those :)
I meant HTML attributes to the form tag, like e.g. 
`<form class="MY-PAYMENT-CLASS" data="PAYMENTMETHODS"></form>`
But as mentioned I can just use Javascript to do so. 
Also being able to add add code to the head of the DOM but that isn't that important as it can be done via JS anyway and as it is a JS based payment provider, it won't work without JS :)

And yes, you are right about GET, I missed the check for only a.btn-action and not just .btn-action part in the code.
