### ISSUE TITLE
Several COUPON issues

### ISSUE THREAD

**Issue by vmans** [aimeos/aimeos-core#87]
Using 17.2.1.

In the demo shop it goes wrong with coupons. You can add a coupon (e.g. "percent") but hitting the cross to remove does not work on http://typo3.demo.aimeos.org/demo/detail/d/1/Demo_article/0/

I had a similar setup, but needed to change it because of this. But now I don't get any further than making a coupon product like this:
- a normal product, type Article, with code "hithere123"
- creating a Coupon with provider "PercentRebate", give it percentrebate.rebate = 50 and percentrebate.productcode = "hithere123", setting Code under tab Codes to "hithere123"
- then have to hide it from catalog list with CSS

This is not the way it should be.

But there is no clear documentation.
I have no other configuration working, but again, it's not working on your demo either.

**Comment by aimeos** [comment]
The demo issue was problem related to Apache/PHP-FPM/RealUrl because
`http://typo3.demo.aimeos.org/demo/basket/bt/coupon-delete///fixed`
led to a `Primary script unknown` returned by PHP-FPM due to the empty segments (`///`). After modifying the RealUrl config by removing `array( 'GETvar' => 'ai[b_coupon]' ),` from the "bt" configuration and clearing the RealUrl tables, it works again.

Maybe we should avoid empty segments in paths

**Comment by vmans** [comment]
That leads to this url, in my case:
`https://.../webshop/mandje/bt/coupon-delete///?ai%5Bb_coupon%5D=hithere123 `

Still /// empty segments. So that won't work I guess?

(I use PHP-FPM indeed.)

**Comment by aimeos** [comment]
Did you empty the `tx_realurl_*` tables?

**Comment by vmans** [comment]
`https://.../webshop/mandje/bt/coupon-delete///hithere123` became `https://.../webshop/mandje/bt/coupon-delete///?ai%5Bb_coupon%5D=hithere123`, so yes I guess?

I found no traces of the old speaking_url in the `tx_realurl_*` tables.

But I was able to change /// into / in the tx_realurl_urldata table and now it works.

**Comment by vmans** [comment]
And now I can create a coupon with a product code that is not the same as the coupon code (no idea but it seems related).

By the way:

I was surprised to see that a Coupon is basically handled as a product in stead of a method. It's probably an okay approach. I remember software 10 years back where we used "products" with negative prices for the same purpose. But overall, it doesn't feel right.

At this moment, the out of the box coupon has a tough logic. For instance:
- It's added up with the total of goods.
- How to explain to a customer that he must create a coupon method plus a coupon product, with stock and numbering with the productcode as the key.

Or do I miss something (documentation seems incomplete)?

**Comment by aimeos** [comment]
Using rebate products is a very flexible approach and it's compliant to existing logistic systems.

If you create your own coupon provider, you can use another approach in your code. The coupon infrastructure and the existing providers are located there:
https://github.com/aimeos/aimeos-core/tree/master/lib/mshoplib/src/MShop/Coupon/Provider

Documentation for the existing coupon providers and their decorators is available here:
https://aimeos.org/docs/User_Manual#Managing_content
