### ISSUE TITLE
[Feature] Handle tax properly by excluding tax for foreign countries and adding option to not show tax (e.g. Kleinunternehmerregelung)

### ISSUE THREAD

**Issue by faerietree** [aimeos/aimeos-core#93]
https://aimeos.org/docs/Configuration/Core/mshop/price shows already a related global setting:
* `mshop/price/taxflag` Configuration setting if prices are [defined] inclusive or exclusive tax 

It would be nice to have these new options:
---
If "Kleinunternehmen"
*  `mshop/price/tax/exclude` Whether tax is excluded or included (default) in summaries, invoice, ... (effectively toggling e.g. German "Kleinunternehmerregelung" but useful for other countries too)

Else more fine-grained tuning if not "Kleinunternehmen", i.e. sales > 17 500 € / year:
* `mshop/price/tax/excude_if_foreign_company_but_within_free_trade_zone` Configuration setting whether prices are inclusive or exclusive tax if `customer.company != '' && customer.country != shop.legal_address.country && customer.country in shop.legal_address.free_trade_zone && is_valid(customer.company_tax_number)`
For checking if a tax number is valid, we could use this site if `free_trade_zone == EU`:
http://ec.europa.eu/taxation_customs/vies/?locale=de

Never show tax for companies from foreign countries: 
---
A  config setting `mshop/price/tax/excude_if_outside_free_trade_zone` is superfluous here because a foreign company needs not pay this tax in foreign countries. It must pay it in its own country.

**Comment by faerietree** [comment]
I think for an easier implementation we should not support the free trade zone stuff. It's finally the responsibility of the selling company to check the tax numbers and demand the tax from _scam_ companies in the aftermath.

**Comment by aimeos** [comment]
Almost all you describe (and a bit more) is implemented by the ai-vatcheck extension offered by the Aimeos company: https://aimeos.com/extensions/

**Comment by faerietree** [comment]
Incredible. I'm stunned. I will have a look.
