### ISSUE TITLE
[Feature] Handle transaction issues | returns

### ISSUE THREAD

**Issue by faerietree** [aimeos/aimeos-core#96]

**Comment by aimeos** [comment]
What does this mean?

**Comment by faerietree** [comment]
Sorry, not directly obvious: It means that if something goes wrong with a Product it can e.g. be returned (you know like other well known shops do it).

**Comment by aimeos** [comment]
Up to now, you can set the delivery status of the order or the delivery status of a single product to "returned" (or other values for refused, lost, etc.). Is that what you thought about?

**Comment by faerietree** [comment]
hm. That's the shop owner position. Initially I thought about the customer point of view - to get to a more automated procedure. But on a 2nd thought I think the return status is enough. Maybe all that customer return functionality on Amazon & Co is a bit superfluous.
Thanks.
