### ISSUE TITLE
[BUG] Bootstrap: Manifest files may not be sorted (missing ksort)

### ISSUE THREAD

**Issue by AndreasA** [aimeos/aimeos-core#97]
In getI18nList the retrieved files by the \DirectoryIterator class are ordered by using ksort at the end, see:
https://github.com/aimeos/aimeos-core/blob/master/Bootstrap.php#L242

However, the same is not done for getManifests:

a simple ksort($manifests) before the return statement should fix this.

Without this change the manifests can be returned in basically random order as it depends on the file sytem.

Which might result in Javascript dependencies being loaded wrong (or other issues in that regard), e.g. I currently have a loading issue here in combination with ai-customergroups. It is currently loaded before ai-admin-extadm which results in missing Javascript code.
Of course, if ai-customergroups would make the ai-admin-extadm a dependency this wouldn't be an issue either but still loading it in alphabetical order would be best.

The bug is in 2016 and 2017.

**Comment by nos3** [comment]
The manifest files are ordered according to their dependencies. In this case, the dependency to "ai-admin-extadm" was missing. This is fixed now for the 2016 and 2017 branches of ai-customergroups.

**Comment by AndreasA** [comment]
True but I still think that the original ordering would make more sense to be alphabetically instead of "random".

**Comment by aimeos** [comment]
No, sorting the manifests alphabetically won't work because extensions are named by their creators and prefixed with their abbreviation, e.g. `aa-myext` and this extension may depend on `ai-client-html`. The setup tasks have the same dependency system and they also can't be sorted by name for the same reason.

The ISO language codes in `getI18nList()` are sorted by name instead of dependencies to get a nice list (de, en, fr, etc.) for the user. The list of language directories returned by `getI18nPaths()` is sorted by dependencies again.

**Comment by AndreasA** [comment]
I know sorting by name alone won't work but I would still sort them prior to resolving dependencies. Though it really isn't that important.

@nos3 Thanks for the quick fix. Backend works again with it :)

**Comment by AndreasA** [comment]
However, maybe instead you could modify the dependency system to load all core extensions prior to custom extensions like TYPO3 does?

**Comment by aimeos** [comment]
The list of Aimeos extensions is quite long: https://github.com/aimeos?utf8=%E2%9C%93&tab=repositories&type=public

Unfortunately, filtering by prefix won't work too because people started to name their extension ai-... as well :-/

**Comment by AndreasA** [comment]
TYPO3 does it by creating a own composer type for the internal sysexts. That value can then by checked during dependency ordering
