### ISSUE TITLE
Scheduler customer related task failure and TYPO3 accounts are no longer created (since 17_7).

### ISSUE THREAD

**Issue by faerietree** [aimeos/aimeos-core#98]
initially created in https://github.com/aimeos/ai-client-html/issues/35 and a pull request set forth to https://github.com/aimeos/ai-typo3/pull/5

Turned out to be a more global issue, thus now in aimeos-core.

May be valid only for TYPO3 < 8 as @worlddevelopment still is on T3 7.x.

**Comment by aimeos** [comment]
The necessary new column for the TYPO3 fe_users table is in the ext_tables.sql file and is added when updating the extension via the TYPO3 Extension Manager or deactivating/activating the extension

**Comment by aimeos** [comment]
Fixed by https://github.com/aimeos/ai-typo3/pull/6
